// <auto-generated />
using System;
using AnalyticsMicroservice.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsMicroservice.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnalyticsMicroservice.Models.CategoryModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<uint?>("ParentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("parent_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Name = "",
                            UserId = 0u
                        });
                });

            modelBuilder.Entity("AnalyticsMicroservice.Models.LocationModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<uint?>("ParentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("parent_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Name = "",
                            UserId = 0u
                        });
                });

            modelBuilder.Entity("AnalyticsMicroservice.Models.MatrixModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("matrices");
                });

            modelBuilder.Entity("AnalyticsMicroservice.Models.PriceModel", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("CategoryId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("category_id");

                    b.Property<uint>("LocationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("location_id");

                    b.Property<uint>("MatrixId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("matrix_id");

                    b.Property<double?>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("prices");
                });
#pragma warning restore 612, 618
        }
    }
}
